"use client";
import {useMemo,useState} from "react";
type InputDef={key:string;label:string;unit:string;default:number;min?:number;step?:number};
type CalcResult={value:number;unit:string;sub?:string};
type CalcDef={id:string;category:string;name:string;description:string;formula:string;inputs:InputDef[];calculate:(v:Record<string,number>)=>CalcResult;note:string};
const n=(v:number,d=2)=>Number.isFinite(v)?Number(v.toFixed(d)):0;
const calcs:CalcDef[]=[
 {id:"grille",category:"換気・ダクト",name:"ガラリ必要開口面積",description:"必要風量、通過風速、有効開口率から外形開口を求める",formula:"A = Q ÷ (3,600 × V × η)",inputs:[{key:"q",label:"風量",unit:"m³/h",default:5000},{key:"v",label:"通過風速",unit:"m/s",default:2.5,min:.1,step:.1},{key:"r",label:"有効開口率",unit:"%",default:50,min:1}],calculate:x=>{const a=x.q/(3600*x.v*(x.r/100));const s=Math.ceil(Math.sqrt(a)*100);return{value:n(a,3),unit:"m²",sub:"正方形換算：約 "+s*10+" × "+s*10+" mm"}},note:"有効開口率はガラリ承認図を使用。防虫網、雨除け、圧力損失を別途確認。"},
 {id:"grille-q",category:"換気・ダクト",name:"ガラリ通過風量",description:"開口寸法から通過可能な風量を求める",formula:"Q = W × H × η × V × 3,600",inputs:[{key:"w",label:"開口幅",unit:"mm",default:1000,min:1},{key:"h",label:"開口高さ",unit:"mm",default:800,min:1},{key:"r",label:"有効開口率",unit:"%",default:50,min:1},{key:"v",label:"通過風速",unit:"m/s",default:2.5,min:.1,step:.1}],calculate:x=>({value:n((x.w/1000)*(x.h/1000)*(x.r/100)*x.v*3600,0),unit:"m³/h"}),note:"許容風速は騒音、雨水侵入、用途、メーカー圧損資料で決定。"},
 {id:"rect-duct",category:"換気・ダクト",name:"角ダクト必要断面積",description:"風量と設計風速から必要断面積を求める",formula:"A = Q ÷ (3,600 × V)",inputs:[{key:"q",label:"風量",unit:"m³/h",default:5000},{key:"v",label:"設計風速",unit:"m/s",default:6,min:.1,step:.1}],calculate:x=>{const a=x.q/(3600*x.v);return{value:n(a,3),unit:"m²",sub:"正方形換算：約 "+Math.ceil(Math.sqrt(a)*100)+"0 mm角"}},note:"実寸はアスペクト比、圧力損失、騒音、天井納まりで決定。"},
 {id:"round-duct",category:"換気・ダクト",name:"丸ダクト必要直径",description:"風量と設計風速から丸ダクト内径を求める",formula:"D = √{4Q ÷ (3,600πV)}",inputs:[{key:"q",label:"風量",unit:"m³/h",default:2000},{key:"v",label:"設計風速",unit:"m/s",default:6,min:.1,step:.1}],calculate:x=>({value:n(Math.sqrt(4*x.q/(3600*Math.PI*x.v))*1000,0),unit:"mm"}),note:"結果以上の標準径を候補とし、圧損計算と騒音条件で確定。"},
 {id:"duct-velocity",category:"換気・ダクト",name:"ダクト内風速",description:"風量と角ダクト寸法から風速を確認する",formula:"V = Q ÷ (3,600 × W × H)",inputs:[{key:"q",label:"風量",unit:"m³/h",default:5000},{key:"w",label:"幅",unit:"mm",default:600,min:1},{key:"h",label:"高さ",unit:"mm",default:400,min:1}],calculate:x=>({value:n(x.q/(3600*(x.w/1000)*(x.h/1000)),2),unit:"m/s"}),note:"吹出口・吸込口・主管・枝管で許容風速は異なる。設計基準を優先。"},
 {id:"vent-ach",category:"換気・ダクト",name:"換気回数から必要風量",description:"室容積と換気回数から換気量を求める",formula:"Q = W × L × H × N",inputs:[{key:"w",label:"室幅",unit:"m",default:5},{key:"l",label:"室奥行",unit:"m",default:8},{key:"h",label:"天井高さ",unit:"m",default:2.7},{key:"ach",label:"換気回数",unit:"回/h",default:6,step:.1}],calculate:x=>({value:n(x.w*x.l*x.h*x.ach,0),unit:"m³/h",sub:"室容積："+n(x.w*x.l*x.h,1)+" m³"}),note:"法定換気量、在室人数、発熱・臭気・局所排気の必要量と比較し、大きい方を採用。"},
 {id:"air-heat",category:"空調",name:"空気の顕熱負荷",description:"風量と温度差から空気の顕熱量を概算する",formula:"Qs = 0.33 × Q × ΔT",inputs:[{key:"q",label:"風量",unit:"m³/h",default:5000},{key:"dt",label:"温度差",unit:"K",default:10,step:.1}],calculate:x=>({value:n(.33*x.q*x.dt/1000,2),unit:"kW"}),note:"0.33は標準空気の概算係数。潜熱を含む全熱負荷ではない。"},
 {id:"fan-power",category:"換気・ダクト",name:"ファン軸動力",description:"風量、全圧、効率から必要動力を概算する",formula:"P = Q × ΔP ÷ η",inputs:[{key:"q",label:"風量",unit:"m³/h",default:10000},{key:"pa",label:"全圧",unit:"Pa",default:500},{key:"e",label:"総合効率",unit:"%",default:60,min:1}],calculate:x=>({value:n((x.q/3600)*x.pa/(x.e/100)/1000,2),unit:"kW"}),note:"モーター容量は余裕率、始動条件、メーカー選定値を含めて決定。"},
 {id:"pipe-velocity",category:"配管",name:"配管内流速",description:"流量と実内径から管内流速を求める",formula:"V = (Q ÷ 3,600) ÷ (πD²/4)",inputs:[{key:"q",label:"流量",unit:"m³/h",default:10},{key:"d",label:"実内径",unit:"mm",default:80,min:.1}],calculate:x=>({value:n((x.q/3600)/(Math.PI*Math.pow(x.d/1000,2)/4),2),unit:"m/s"}),note:"呼び径ではなく実内径を入力。許容流速は用途、騒音、腐食、ウォーターハンマ条件で確認。"},
 {id:"pipe-flow",category:"配管",name:"管径・流速から流量",description:"実内径と流速から通過流量を求める",formula:"Q = πD²/4 × V × 3,600",inputs:[{key:"d",label:"実内径",unit:"mm",default:80,min:.1},{key:"v",label:"流速",unit:"m/s",default:1.5,step:.1}],calculate:x=>({value:n(Math.PI*Math.pow(x.d/1000,2)/4*x.v*3600,2),unit:"m³/h"}),note:"実流量は圧力損失、弁・継手、ポンプ特性との連立で決まる。"},
 {id:"slope",category:"排水",name:"排水勾配の高低差",description:"配管延長と勾配比から必要な落差を求める",formula:"H = L × 1,000 ÷ 勾配比",inputs:[{key:"l",label:"配管延長",unit:"m",default:20},{key:"r",label:"勾配比 1/",unit:"",default:100,min:1}],calculate:x=>({value:n(x.l*1000/x.r,0),unit:"mm",sub:"勾配："+n(100/x.r,2)+"%"}),note:"管底基準で計算。継手段差、施工誤差、管径別の最小・上限勾配を別途確認。"},
 {id:"pump-head",category:"ポンプ・水槽",name:"ポンプ全揚程の概算",description:"実揚程、配管損失、末端必要圧から全揚程を求める",formula:"H = Hs + Hf + Pr ÷ 9.80665",inputs:[{key:"hs",label:"実揚程",unit:"m",default:20},{key:"hf",label:"配管・機器損失",unit:"m",default:8},{key:"p",label:"末端必要圧力",unit:"kPa",default:150}],calculate:x=>{const h=x.hs+x.hf+x.p/9.80665;return{value:n(h,2),unit:"m",sub:"約 "+n(h*9.80665,0)+" kPa"}},note:"吸込条件、流量、同時使用率、NPSH、ポンプ曲線で最終選定。"},
 {id:"water-heat",category:"空調・熱源",name:"水量から熱量",description:"冷温水流量と往還温度差から熱量を求める",formula:"Qh = 1.163 × q × ΔT",inputs:[{key:"q",label:"水量",unit:"m³/h",default:20},{key:"dt",label:"往還温度差",unit:"K",default:5,min:.1,step:.1}],calculate:x=>({value:n(1.163*x.q*x.dt,2),unit:"kW"}),note:"水の密度・比熱を標準値で計算。ブライン等は物性値を変更。"},
 {id:"water-flow-heat",category:"空調・熱源",name:"熱量から必要水量",description:"熱量と往還温度差から冷温水量を求める",formula:"q = Qh ÷ (1.163 × ΔT)",inputs:[{key:"kw",label:"熱量",unit:"kW",default:100},{key:"dt",label:"往還温度差",unit:"K",default:5,min:.1,step:.1}],calculate:x=>({value:n(x.kw/(1.163*x.dt),2),unit:"m³/h"}),note:"実機選定はコイル・熱交換器メーカーの水量、圧損、汚れ係数を優先。"},
 {id:"tank",category:"ポンプ・水槽",name:"受水槽の有効容量概算",description:"一日使用水量と貯留時間から必要有効容量を求める",formula:"V = 日使用量 × 貯留時間 ÷ 24",inputs:[{key:"daily",label:"一日使用水量",unit:"m³/日",default:100},{key:"hours",label:"貯留時間",unit:"h",default:8,step:.5}],calculate:x=>({value:n(x.daily*x.hours/24,2),unit:"m³"}),note:"給水引込能力、ピーク使用、用途、断水対応、自治体・水道事業者基準で決定。"},
 {id:"expansion",category:"配管",name:"配管の熱伸び",description:"線膨張係数、延長、温度差から伸び量を求める",formula:"ΔL = α × L × ΔT",inputs:[{key:"a",label:"線膨張係数",unit:"mm/(m・K)",default:.012,step:.001},{key:"l",label:"配管延長",unit:"m",default:30},{key:"dt",label:"温度差",unit:"K",default:60}],calculate:x=>({value:n(x.a*x.l*x.dt,1),unit:"mm"}),note:"目安：炭素鋼0.012、SUS・銅0.017、硬質塩ビ約0.07。固定点・ガイド・伸縮継手を別途設計。"},
 {id:"surface",category:"数量・保温",name:"円形配管の表面積",description:"外径と延長から保温・塗装の施工面積を求める",formula:"A = π × D × L",inputs:[{key:"d",label:"保温外径・管外径",unit:"mm",default:114.3},{key:"l",label:"延長",unit:"m",default:100}],calculate:x=>({value:n(Math.PI*(x.d/1000)*x.l,2),unit:"m²"}),note:"継手、弁、フランジ、重ね代、ロス率は別途加算。"},
 {id:"duct-surface",category:"数量・保温",name:"角ダクト表面積",description:"ダクト幅・高さ・延長から外周面積を求める",formula:"A = 2(W + H) × L",inputs:[{key:"w",label:"幅",unit:"mm",default:600},{key:"h",label:"高さ",unit:"mm",default:400},{key:"l",label:"延長",unit:"m",default:20}],calculate:x=>({value:n(2*(x.w+x.h)/1000*x.l,2),unit:"m²"}),note:"エルボ、分岐、変形、フランジ、保温重ね代、ロス率は別途加算。"},
 {id:"three-current",category:"電気・機器",name:"三相機器の電流概算",description:"三相電力、電圧、力率、効率から電流を求める",formula:"I = P ÷ (√3 × V × cosφ × η)",inputs:[{key:"kw",label:"軸出力",unit:"kW",default:7.5},{key:"v",label:"電圧",unit:"V",default:200,min:1},{key:"pf",label:"力率",unit:"%",default:85,min:1},{key:"e",label:"効率",unit:"%",default:90,min:1}],calculate:x=>({value:n(x.kw*1000/(Math.sqrt(3)*x.v*(x.pf/100)*(x.e/100)),1),unit:"A"}),note:"概算値。ブレーカ、配線、始動電流、インバータ条件は電気設計・機器仕様を優先。"}
];
export default function CalculatorHub(){
 const [category,setCategory]=useState("すべて"),[query,setQuery]=useState(""),[selected,setSelected]=useState("grille");
 const [values,setValues]=useState<Record<string,number>>({});
 const categories=["すべて",...Array.from(new Set(calcs.map(x=>x.category)))];
 const visible=calcs.filter(x=>(category==="すべて"||x.category===category)&&(!query||(x.name+x.description+x.formula).toLowerCase().includes(query.toLowerCase())));
 const calc=calcs.find(x=>x.id===selected&&visible.some(v=>v.id===x.id))||visible[0]||calcs[0];
 const inputValues=useMemo(()=>Object.fromEntries(calc.inputs.map(i=>[i.key,values[calc.id+":"+i.key]??i.default])),[calc,values]);
 const result=calc.calculate(inputValues);
 const update=(key:string,value:string)=>setValues({...values,[calc.id+":"+key]:Number(value)});
 return <div className="page calculatorPage"><div className="pageTitle"><div><span className="eyebrow">EQUIPMENT CALCULATORS</span><h2>設備計算ツール集</h2><p>数字を入力すると、式・単位・答えを自動計算</p></div><b className="calcCount">{calcs.length}計算</b></div>
  <section className="calcSearch"><input aria-label="計算式を検索" value={query} onChange={e=>setQuery(e.target.value)} placeholder="例：ガラリ、風量、配管流速、揚程"/><div>{categories.map(x=><button key={x} className={category===x?"active":""} onClick={()=>setCategory(x)}>{x}</button>)}</div></section>
  <div className="calcLayout"><aside className="calcIndex">{visible.map(x=><button key={x.id} className={calc.id===x.id?"active":""} onClick={()=>setSelected(x.id)}><small>{x.category}</small><b>{x.name}</b><span>{x.description}</span></button>)}</aside>
   <article className="calcPanel"><header><span>{calc.category}</span><h3>{calc.name}</h3><p>{calc.description}</p></header><div className="formulaBox"><small>計算式</small><strong>{calc.formula}</strong></div>
    <div className="calcInputs">{calc.inputs.map(i=><label key={i.key}><span>{i.label}</span><div><input inputMode="decimal" type="number" min={i.min??0} step={i.step??1} value={inputValues[i.key]} onChange={e=>update(i.key,e.target.value)}/><b>{i.unit}</b></div></label>)}</div>
    <section className="calcResult"><small>計算結果</small><div><strong>{result.value.toLocaleString()}</strong><b>{result.unit}</b></div>{result.sub&&<p>{result.sub}</p>}</section><section className="calcNote"><b>現場での注意</b><p>{calc.note}</p></section>
   </article></div>{!visible.length&&<p className="empty">一致する計算式がありません</p>}<p className="caution">計算結果は施工検討の初期値です。法令、設計図書、特記仕様書、メーカー承認図、自治体・水道事業者・消防の基準を優先してください。</p></div>
}
