"use client";
import {useMemo,useState} from "react";

type ProcessStep={phase:string;title:string;detail:string};
type Detail={id:string;category:string;title:string;aliases:string[];summary:string;timing:string;process?:ProcessStep[];building:string[];equipment:string[];checks:string[];basis:string;source:string;url:string;diagram:string};
const details:Detail[]=[
 {id:"ac-drain",category:"空調",title:"天井内空調ドレン",aliases:["ドレン配管","室内機ドレン","結露水"],summary:"室内機から排水先まで連続した下り勾配を確保し、山越え・逆勾配・たるみを作らない。",timing:"天井LGS施工前に高さと経路を確定し、天井閉塞前に通水試験。",building:["天井伏図・点検口位置を確定","梁下と天井仕上げ間の有効寸法を確認","点検口からトラップ・ポンプへ手が届くようにする"],equipment:["原則1/100以上を計画目安とし機器要領を優先","負圧機器は必要封水深を確保","保温継目を密着し結露試験を行う"],checks:["管底高さ","勾配の実測","通水・漏水","点検口からの作業性"],basis:"一般目安＋メーカー基準",source:"公共建築工事標準仕様書（機械設備工事編）",url:"https://www.mlit.go.jp/gobuild/gobuild_tk6_000058.html",diagram:"drain"},
 {id:"pump",category:"衛生",title:"ポンプ吸込・吐出配管",aliases:["ポンプ廻り","偏心レジューサ","防振継手"],summary:"配管荷重をポンプへ掛けず、吸込側に空気溜まりを作らない。弁類と逆止弁は点検可能に配置する。",timing:"基礎寸法と機器芯を確定後、ポンプ据付・芯出しを行ってから配管接続。",building:["基礎天端・アンカー・排水溝を確認","搬入・更新経路を確保","漏水時の排水先を確保"],equipment:["吸込偏心レジューサの平側を上にすることを基本","防振継手に配管荷重を掛けない","接続後に再芯出しを実施"],checks:["流れ方向","ストレーナ清掃空間","逆止弁向き","圧力計・温度計位置"],basis:"標準仕様",source:"公共建築設備工事標準図（機械設備工事編）",url:"https://www.mlit.go.jp/gobuild/gobuild_tk4_000021.html",diagram:"pump"},
 {id:"steam",category:"空調",title:"蒸気主管・ドリップレッグ",aliases:["蒸気配管","ウォーターハンマ","蒸気トラップ"],summary:"凝縮水を滞留させず、低部・立下り前・主管末端からドリップを取り出してトラップへ導く。",timing:"支持・固定点・熱伸縮計画を先に承認し、配管施工後に暖管・作動確認。",building:["貫通部の熱伸縮余裕を確認","高温部の接触防止と点検空間を確保","トラップ排出先を事前調整"],equipment:["蒸気流れ方向への下りを基本","固定・ガイド・ローラーを役割別に配置","トラップ前後に点検・交換用弁を計画"],checks:["管径・圧力・温度","トラップ形式","ドレン排出先","保温外装・火傷防止"],basis:"設計・承認図優先",source:"公共建築工事標準仕様書（機械設備工事編）",url:"https://www.mlit.go.jp/gobuild/gobuild_tk6_000058.html",diagram:"steam"},
 {id:"toilet",category:"衛生",title:"壁掛衛生器具の納まり",aliases:["壁掛便器","洗面器","手洗器","器具芯"],summary:"仕上げ面基準で器具芯・給排水芯・取付高さを合わせ、壁下地へ荷重を伝える。",timing:"LGS閉塞前に器具承認図で芯・補強・配管位置を墨出し確認。",building:["仕上げ厚を含む壁面基準を共有","壁下地・補強材・アンカー位置を確定","手すり・紙巻器・鏡との干渉を確認"],equipment:["器具付属金物を使用","給排水芯の許容差を承認図で確認","シール後に漏水・がたつきを確認"],checks:["FL基準高さ","壁仕上げ厚","補強写真","通水・封水"],basis:"承認図優先",source:"公共建築設備工事標準図（機械設備工事編）",url:"https://www.mlit.go.jp/gobuild/gobuild_tk4_000021.html",diagram:"fixture"},
 {id:"fire-damper",category:"ダクト",title:"防火ダンパー・防火区画貫通",aliases:["FD","防火ダンパ","区画貫通"],summary:"防火区画位置に適合する認定・仕様で設置し、作動・復帰・交換ができる点検口を設ける。",timing:"区画壁の位置確定後、壁閉塞前にスリーブ・補強・点検口を調整。",building:["区画線と壁厚を確認","開口補強と埋戻し範囲を確認","点検口をダンパ操作部正面に配置"],equipment:["ダンパを区画に近接配置","温度ヒューズ・作動機構を点検可能にする","ダクト荷重を区画壁へ掛けない"],checks:["区画種別","ダンパ向き","点検口寸法","作動試験・表示"],basis:"法令・認定条件",source:"公共建築設備工事標準図（機械設備工事編）",url:"https://www.mlit.go.jp/gobuild/gobuild_tk4_000021.html",diagram:"damper"},
 {id:"sleeve",category:"共通",title:"配管の壁・床貫通",aliases:["スリーブ","防火区画","止水つば","貫通処理"],summary:"管種・口径・保温・開口・壁床厚を認定条件と照合し、認定範囲内の材料と配置で施工する。",timing:"コンクリート打設・壁閉塞前に位置と開口寸法を確定し、施工後に認定表示と写真を残す。",building:["構造鉄筋・開口補強を確認","防水範囲は止水つば・防水納まりを確認","壁仕上げと化粧プレート範囲を確認"],equipment:["保温を含む外径で開口選定","複数管の離隔を認定書で確認","冷媒管は対応する耐火キャップ等を選定"],checks:["認定番号","壁床厚","管種・口径","施工前中後写真"],basis:"法令・認定条件",source:"国土交通省 防火設備・標準仕様関連",url:"https://www.mlit.go.jp/gobuild/gobuild_tk6_000058.html",diagram:"sleeve"},
 {id:"tank",category:"衛生",title:"受水槽まわりの納まり",aliases:["FRP水槽","受水槽","メンテナンススペース"],summary:"六面点検、マンホール出入り、弁操作、パネル交換ができる有効空間と搬出経路を確保する。",timing:"機械室躯体・基礎施工前に水槽分割、搬入、組立、更新経路まで確認。",building:["上部・側面・底面の点検空間を確保","基礎寸法・レベル・床防水を確認","将来パネルを搬出できる経路を確保"],equipment:["オーバーフローは間接排水","吐水口空間を確保","電極・定水位弁を交換可能に配置"],checks:["有効点検寸法","マンホール開閉","基礎レベル","排水口空間"],basis:"法令・自治体・メーカー基準",source:"公共建築工事標準仕様書（機械設備工事編）",url:"https://www.mlit.go.jp/gobuild/gobuild_tk6_000058.html",diagram:"tank"},
 {id:"ahu",category:"空調",title:"空調機・全熱交換器の点検納まり",aliases:["AHU","エアハン","全熱交換器","ロスナイ"],summary:"フィルター・ファン・モーター・熱交換エレメントを取り出せる点検面と搬出経路を確保する。",timing:"吊り込み・据付前に機器承認図を天井伏図・梁図・点検口図へ重ねて調整。",building:["構造体から独立支持","点検扉の全開範囲を確保","フィルター等の引抜き長さを確保"],equipment:["ダクト接続部へ無理な荷重を掛けない","ドレン勾配と封水を確保","電装箱・フィルター側を点検口へ向ける"],checks:["機器重量","吊りボルト径","点検方向","ドレン通水"],basis:"標準仕様＋メーカー基準",source:"公共建築設備工事標準図（機械設備工事編）",url:"https://www.mlit.go.jp/gobuild/gobuild_tk4_000021.html",diagram:"ahu"},
 {id:"machine-foundation",category:"建築取り合い",title:"機械基礎の施工順序",aliases:["機械基礎","機器基礎","コンクリート基礎","あと打ちアンカー"],summary:"機器の芯・重量・アンカー位置と床防水を事前に調整し、配筋から防水復旧までの順序を崩さず施工する。",timing:"機器承認図と基礎図の確定後、機器搬入・据付け前に施工。防水範囲は建築・防水業者と先行調整する。",process:[{phase:"着手前",title:"承認図と建築工程を先に固める",detail:"機器寸法・重量・基礎芯・アンカー位置・防水範囲を確定し、配筋・型枠・CON打設の日程を建築と合わせる。"},{phase:"施工中",title:"次の工程で隠れる前に確認する",detail:"配筋・鉄筋よけ・型枠はCON打設前に検査し写真を残す。打設後は強度発現と養生期間を確保する。"},{phase:"次工程へ",title:"引渡し条件を満たしてから進む",detail:"基礎天端・芯・強度を確認後にあと打ちアンカーを施工。アンカー検査と防水復旧完了後に機器搬入・据付けへ進む。"}],building:["機器承認図から基礎寸法・高さ・芯・機器重量を確定","床配筋・基礎配筋とあと打ちアンカー穿孔位置の干渉を確認","防水層の立上り・端部・復旧方法と施工区分を確定"],equipment:["1．機械基礎配筋","2．型枠","3．鉄筋よけ","4．CON打設","5．あと打ちアンカー施工","6．防水"],checks:["基礎芯・外形寸法・天端高さ","配筋径・ピッチ・かぶり・定着","アンカー位置の鉄筋干渉と穿孔深さ","コンクリート強度・養生・天端レベル","アンカーの種類・径・埋込み・清掃・引張確認","防水端部の連続性・保護・施工後写真"],basis:"設計図・構造図・防水仕様優先",source:"公共建築工事標準仕様書・公共建築設備工事標準図",url:"https://www.mlit.go.jp/gobuild/gobuild_tk6_000058.html",diagram:"machine-foundation"},
 {id:"roof",category:"建築取り合い",title:"屋上配管・ダクト支持基礎",aliases:["屋上架台","防水立上り","押えコンクリート"],summary:"防水層を傷めず、風・地震・熱伸縮に耐える基礎と架台を設け、排水を妨げない。",timing:"防水施工前に基礎位置・高さ・アンカー方法を建築と確定。",building:["防水立上り高さと納まりを確認","ルーフドレンへの排水経路を塞がない","基礎周囲の防水施工幅を確保"],equipment:["異種金属接触を防止","架台の防錆・溶融亜鉛めっきを確認","伸縮方向に合わせ固定・ガイドを配置"],checks:["構造耐力","防水保証条件","基礎天端","保守通路"],basis:"設計図・防水メーカー優先",source:"公共建築工事標準仕様書（機械設備工事編）",url:"https://www.mlit.go.jp/gobuild/gobuild_tk6_000058.html",diagram:"roof"},
 {id:"ceiling",category:"建築取り合い",title:"システム天井内の設備配置",aliases:["グリッド天井","天井伏図","点検口"],summary:"照明・感知器・吹出口・スプリンクラーをモジュールに合わせ、荷重は天井下地と分離する。",timing:"天井下地着手前に総合図で器具割付と吊り位置を確定。",building:["天井モジュールと器具寸法を照合","天井下地へ設備荷重を預けない","点検・交換できる開口を確保"],equipment:["吹出口と照明・感知器の離隔を調整","フレキは過度に曲げない","ダンパ・弁を点検可能に配置"],checks:["天井伏図承認","吊り干渉","器具芯","点検動線"],basis:"総合図・承認図優先",source:"公共建築設備工事標準図（機械設備工事編）",url:"https://www.mlit.go.jp/gobuild/gobuild_tk4_000021.html",diagram:"ceiling"},
 {id:"floor-drain",category:"衛生",title:"床排水・塗床の納まり",aliases:["床排水口","フロアドレン","塗床","防水"],summary:"仕上げ床の水勾配を排水口へ集め、防水層・塗床端部を排水金物へ確実に納める。",timing:"土間・防水・塗床施工前に排水口天端と仕上げ厚を建築へ提示。",building:["仕上げ厚を含む排水口天端を確定","防水層の押え・端部納まりを確認","床勾配範囲と水下位置を共有"],equipment:["排水口を固定し打設時の浮きを防止","養生してモルタル流入を防止","施工後に通水・水溜まりを確認"],checks:["FLとの差","排水口レベル","防水端部","水張り・通水"],basis:"設計・防水仕様優先",source:"公共建築設備工事標準図（機械設備工事編）",url:"https://www.mlit.go.jp/gobuild/gobuild_tk4_000021.html",diagram:"floor"},
 {id:"vent-cap",category:"ダクト",title:"ベントキャップ（ベンドキャップ）外壁貫通",aliases:["ベンドキャップ","ベントキャップ","外壁フード","ダクト外壁貫通"],summary:"外壁貫通部は、穴埋め・一次シール・本体取付・二次シールの順で雨水浸入を防ぐ。シールは連続させ、空隙や水溜まりを残さない。",timing:"ダクト貫通後、外壁仕上げとシール施工条件を確認してから取付。足場解体・外壁検査前に散水確認を完了する。",building:["外壁仕上げ面・開口寸法・下地位置を確認","穴埋めは外壁面より1cm下げてシール代を確保","外壁材とシール材の適合、プライマー、施工区分を確認","水切り・外壁目地・他の開口部と干渉させない"],equipment:["1．ダクト貫通","2．穴埋め（外壁面より1cm下げる）","3．一次シール（耐火シールを使用）","4．ベントキャップ取付（背面にバッカーを付ける）","5．二次シール"],checks:["穴埋めの下げ寸法1cm","一次シールの連続性・充填状態","背面バッカーの取付状態","本体の固定・向き・水切り","二次シールの切れ・ピンホール・三面接着防止","施工後の散水確認と写真記録"],basis:"指定施工要領＋採用製品・外壁仕様優先",source:"公共建築工事標準仕様書（機械設備工事編）",url:"https://www.mlit.go.jp/gobuild/gobuild_tk6_000058.html",diagram:"vent-cap"},
 {id:"hanger",category:"共通",title:"配管・ダクトの吊り支持",aliases:["全ねじ","吊りバンド","振れ止め","架台"],summary:"満水・保温・弁類を含む重量と地震時荷重を構造体へ伝え、用途に応じて固定・ガイド・振れ止めを設ける。",timing:"インサート・アンカー施工前に梁・スラブ・他設備と支持位置を調整。",building:["構造体への固定方法を確認","デッキ・PC・耐火被覆への施工可否を確認","天井下地と支持を共用しない"],equipment:["管径・材質別の支持間隔を守る","弁・分岐・曲がり・可とう継手付近を追加支持","保温厚を含むバンド径を選定"],checks:["吊り荷重","全ねじ径","アンカー耐力","振れ止め位置"],basis:"標準仕様＋耐震計算",source:"公共建築工事標準仕様書（機械設備工事編）",url:"https://www.mlit.go.jp/gobuild/gobuild_tk6_000058.html",diagram:"hanger"}
];

export default function InstallationDetailBook(){
 const [query,setQuery]=useState(""),[category,setCategory]=useState("すべて"),[selected,setSelected]=useState(details[0].id);
 const filtered=useMemo(()=>details.filter(x=>(category==="すべて"||x.category===category)&&(!query||[x.title,x.category,...x.aliases,x.summary,...x.checks].join(" ").toLowerCase().includes(query.toLowerCase()))),[query,category]);
 const item=filtered.find(x=>x.id===selected)||filtered[0]||details.find(x=>x.id===selected)||details[0];
 return <div className="page detailBookPage"><div className="pageTitle"><div><span className="eyebrow">INSTALLATION DETAIL GUIDE</span><h2>設備施工要領図集</h2><p>納まり・施工時期・他業者との取り合いを独自図解で確認</p></div><b className="detailCount">{details.length}要領</b></div>
  <section className="detailNotice"><b>図だけで決めず、確認順まで見る</b><p>書籍の転載ではありません。官公庁基準とメーカー資料をもとに、現場で使いやすい独自文章・模式図として整理しています。</p></section>
  <section className="detailSearch"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="例：ドレン、ポンプ、塗床、区画貫通"/><div>{["すべて",...Array.from(new Set(details.map(x=>x.category)))].map(x=><button key={x} className={category===x?"active":""} onClick={()=>setCategory(x)}>{x}</button>)}</div></section>
  <div className="detailBookLayout"><aside>{filtered.map(x=><button key={x.id} className={item.id===x.id?"active":""} onClick={()=>setSelected(x.id)}><span>{x.category}</span><b>{x.title}</b><small>{x.aliases.join("・")}</small></button>)}{!filtered.length&&<p>該当する要領がありません</p>}</aside>
   <article className="detailSheet"><header><span>{item.category}</span><h3>{item.title}</h3><p>{item.aliases.join("・")}</p></header><DetailDiagram id={item.diagram} title={item.title}/>
    <p className="detailSummary">{item.summary}</p><section className="detailTiming"><span>施工タイミング</span><b>{item.timing}</b></section>
    {item.process&&<section className="processThinking"><h4>工程の考え方</h4><div>{item.process.map((step,i)=><article key={step.phase}><span>{i+1}</span><div><small>{step.phase}</small><b>{step.title}</b><p>{step.detail}</p></div></article>)}</div></section>}
    <div className="detailColumns"><DetailBlock title="建築・他業者との取り合い" items={item.building}/><DetailBlock title="設備施工の要点" items={item.equipment}/></div>
    <section className="detailChecklist"><h4>現場チェック</h4>{item.checks.map((x,i)=><label key={x}><input type="checkbox"/><span>{i+1}</span>{x}</label>)}</section>
    <footer><span>{item.basis}</span><a href={item.url} target="_blank" rel="noopener noreferrer">根拠資料：{item.source} ↗</a></footer>
   </article>
  </div><p className="caution">数値・適用範囲は、設計図書、特記仕様書、所轄官庁、認定書、採用製品の承認図・施工要領を優先してください。</p>
 </div>
}
function DetailBlock({title,items}:{title:string;items:string[]}){return <section><h4>{title}</h4><ol>{items.map(x=><li key={x}>{x}</li>)}</ol></section>}
function DetailDiagram({id,title}:{id:string;title:string}){
 const labels:Record<string,string>={drain:"室内機から排水先まで連続下り",pump:"吸込側に空気溜まりを作らない",steam:"主管低部から凝縮水を排出",fixture:"壁下地へ器具荷重を伝える",damper:"区画直近にFD・点検口を配置",sleeve:"壁厚・管種に合う認定処理",tank:"六面点検とオーバーフロー空間",ahu:"点検面と引抜き方向を確保","machine-foundation":"配筋から防水までの施工順序",roof:"防水層を切らない独立基礎",ceiling:"天井グリッドに器具を整列",floor:"仕上げ勾配を排水口へ集める","vent-cap":"穴埋め→一次→本体→二次シール",hanger:"構造体から独立吊り・振れ止め"};
 const scene=()=>{switch(id){
  case"drain":return <><div className="d-unit">室内機</div><div className="d-pan">ドレンパン</div><div className="d-pipe"/><div className="d-out">排水先</div><div className="d-arrow">勾配 1/100以上 →</div><div className="d-ng">山越え・たるみ NG</div></>;
  case"pump":return <><div className="p-suction">吸込管</div><div className="p-reducer">偏心レジューサ<br/>平側上</div><div className="p-pump">P</div><div className="p-motor">M</div><div className="p-discharge">吐出管 ↑</div><div className="p-valve">逆止弁＋仕切弁</div><div className="p-base">基礎・防振</div></>;
  case"steam":return <><div className="s-main">蒸気主管　流れ →</div><div className="s-slope">流れ方向へ下り</div><div className="s-leg">ドリップ<br/>レッグ</div><div className="s-trap">蒸気<br/>トラップ</div><div className="s-return">還水へ →</div></>;
  case"fixture":return <><div className="f-wall">LGS壁＋補強</div><div className="f-carrier">取付金物</div><div className="f-bowl">壁掛器具</div><div className="f-water">給水</div><div className="f-drain">排水</div><div className="f-floor">仕上げFL</div><div className="f-height">承認図の高さ</div></>;
  case"damper":return <><div className="fd-wall">防火区画壁</div><div className="fd-duct">ダクト</div><div className="fd-body">FD</div><div className="fd-blades">╱╱╱</div><div className="fd-access">点検口</div><div className="fd-clear">作動・復帰・交換</div></>;
  case"sleeve":return <><div className="sl-wall">壁／床<br/>認定構造</div><div className="sl-sleeve">スリーブ</div><div className="sl-pipe">配管＋保温</div><div className="sl-seal left">認定<br/>充填材</div><div className="sl-seal right">認定<br/>充填材</div><div className="sl-note">開口・離隔・支持を認定図と照合</div></>;
  case"tank":return <><div className="t-clear top">上部点検 1000mm目安</div><div className="t-tank">受水槽<div>マンホール</div></div><div className="t-side left">600mm目安</div><div className="t-side right">600mm目安</div><div className="t-base">基礎</div><div className="t-overflow">OF →　吐水口空間</div></>;
  case"ahu":return <><div className="a-slab">構造スラブ</div><div className="a-rods">│　│　　　│　│</div><div className="a-unit"><span>FILTER</span><span>COIL</span><span>FAN</span></div><div className="a-pull">← フィルター引抜き空間</div><div className="a-duct left">RA</div><div className="a-duct right">SA</div><div className="a-drain">ドレン → Uトラップ</div></>;
  case"machine-foundation":return <><div className="mf-sequence"><span><b>1</b>機械基礎配筋</span><i>→</i><span><b>2</b>型枠</span><i>→</i><span><b>3</b>鉄筋よけ</span><i>→</i><span><b>4</b>CON打設</span><i>→</i><span><b>5</b>あと打ちアンカー施工</span><i>→</i><span><b>6</b>防水</span></div><div className="mf-note">基礎芯・天端・アンカー位置・防水復旧を各工程で確認</div></>;
  case"roof":return <><div className="r-pipe">配管／ダクト</div><div className="r-support">架台</div><div className="r-base">独立基礎</div><div className="r-waterproof">防水層立上り</div><div className="r-slab">屋上スラブ</div><div className="r-flow">雨水 → ルーフドレン</div></>;
  case"ceiling":return <><div className="c-grid"><i/><i/><i/><i/><i/><i/></div><div className="c-light">照明</div><div className="c-diffuser">吹出口</div><div className="c-sprinkler">●<br/>SP</div><div className="c-detector">○<br/>感知器</div><div className="c-rods">独立吊り</div></>;
  case"floor":return <><div className="fl-wall">壁</div><div className="fl-finish left">仕上げ床 ↘</div><div className="fl-finish right">↙ 仕上げ床</div><div className="fl-drain">目皿<br/>排水口</div><div className="fl-waterproof">防水層・塗床端部</div><div className="fl-pipe">排水管</div><div className="fl-level">天端＝仕上げ水下</div></>;
  case"vent-cap":return <><div className="v-inside">屋内</div><div className="v-wall">外壁</div><div className="v-duct">ダクト →</div><div className="v-fill">穴埋め<br/>1cm下げ</div><div className="v-primary">①耐火<br/>シール</div><div className="v-backer">②バッカー</div><div className="v-cap">③ベント<br/>キャップ</div><div className="v-secondary">④二次シール</div><div className="v-outside">屋外・雨</div></>;
  default:return <><div className="h-slab">構造スラブ</div><div className="h-anchor">アンカー</div><div className="h-rods">全ねじ　　全ねじ</div><div className="h-brace">振れ止め</div><div className="h-trapeze">アングル架台</div><div className="h-pipe">配管／ダクト</div><div className="h-ceiling">天井下地とは分離</div></>;
 }};
 return <figure className={`detailDiagram technical ${id}`} aria-label={`${title}の施工模式図`}><figcaption><b>{title}</b><span>{labels[id]||labels.hanger}</span></figcaption><div className="diagramScene">{scene()}</div><div className="diagramLegend"><span><i className="building"/>建築・構造</span><span><i className="equipment"/>設備</span><span><i className="seal"/>処理・点検</span></div></figure>;
}
