"use client";
import {useEffect,useRef,useState} from "react";
type ActionItem={task:string;assignee:string;due:string};
type Draft={summary:string;decisions:string[];actions:ActionItem[];pending:string[];speakers:string[];source?:"ai"|"local"};
type Minute=Draft&{id:number;title:string;date:string;participants:string;transcript:string;duration:number;audioUrl?:string;createdAt:string};
const sentences=(t:string)=>t.replace(/\n/g,"。").split(/[。！？!?]/).map(x=>x.trim()).filter(Boolean);
function localAnalyze(text:string):Draft{const s=sentences(text);const taskLines=s.filter(x=>/(担当|までに|期限|提出|手配|作成|連絡|依頼|対応|確認する)/.test(x)).slice(0,12);return{summary:(s.slice(0,4).join("。")+(s.length?"。":"")).slice(0,400),decisions:s.filter(x=>/決定|確定|採用|で進め|了承|承認|ことにする/.test(x)).slice(0,10),actions:taskLines.map(x=>({task:x,assignee:x.match(/(?:^|[、，])([^、，]{1,14}(?:さん|担当|係|会社))/)?.[1]||"未設定",due:x.match(/(?:本日|明日|今週|来週|\d{1,2}月\d{1,2}日|\d{1,2}日まで)/)?.[0]||"未設定"})),pending:s.filter(x=>/未定|保留|検討|要確認|確認が必要|次回|質疑|調整/.test(x)).slice(0,10),speakers:Array.from(new Set(Array.from(text.matchAll(/(?:^|\n)([^：:\n]{1,16})[：:]/g)).map(x=>x[1]))),source:"local"}}
const formatTime=(n:number)=>`${String(Math.floor(n/3600)).padStart(2,"0")}:${String(Math.floor(n%3600/60)).padStart(2,"0")}:${String(n%60).padStart(2,"0")}`;
export default function MeetingMinutesAi(){
 const [recording,setRecording]=useState(false),[seconds,setSeconds]=useState(0),[status,setStatus]=useState("待機中"),[analyzing,setAnalyzing]=useState(false),[saving,setSaving]=useState(false);
 const [title,setTitle]=useState("設備定例会議"),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[participants,setParticipants]=useState(""),[transcript,setTranscript]=useState(""),[draft,setDraft]=useState<Draft|null>(null),[history,setHistory]=useState<Minute[]>([]),[query,setQuery]=useState(""),[audioUrl,setAudioUrl]=useState(""),[copied,setCopied]=useState(false),[consentConfirmed,setConsentConfirmed]=useState(false);
 const mediaRef=useRef<MediaRecorder|null>(null),streamRef=useRef<MediaStream|null>(null),recognitionRef=useRef<any>(null),timerRef=useRef<number|undefined>(undefined),chunksRef=useRef<Blob[]>([]),audioBlobRef=useRef<Blob|null>(null),transcriptRef=useRef("");
 const load=async()=>{try{const r=await fetch("/api/meeting-minutes");const j=await r.json();if(r.ok)setHistory(j.minutes||[])}catch{}};
 useEffect(()=>{load();return()=>{if(timerRef.current)clearInterval(timerRef.current);streamRef.current?.getTracks().forEach(t=>t.stop())}},[]);
 const analyze=async(text=transcriptRef.current)=>{if(!text.trim()){setStatus("文字起こしがありません。会話文を入力してください");return}setAnalyzing(true);setStatus("AIが要約・担当者・期限を整理中…");try{const r=await fetch("/api/meeting-minutes/analyze",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({transcript:text,title,date,participants})});const j=await r.json();if(!r.ok)throw new Error();setDraft(j.minutes);setStatus(j.minutes.source==="ai"?"AI議事録案を作成しました":"議事録案を作成しました（AI未接続のため端末整理）")}catch{setDraft(localAnalyze(text));setStatus("議事録案を作成しました（通信できないため端末整理）")}finally{setAnalyzing(false)}};
 const start=async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});streamRef.current=stream;chunksRef.current=[];audioBlobRef.current=null;if(audioUrl)URL.revokeObjectURL(audioUrl);setAudioUrl("");const recorder=new MediaRecorder(stream);mediaRef.current=recorder;recorder.ondataavailable=e=>{if(e.data.size)chunksRef.current.push(e.data)};recorder.onstop=()=>{const blob=new Blob(chunksRef.current,{type:recorder.mimeType||"audio/webm"});audioBlobRef.current=blob;setAudioUrl(URL.createObjectURL(blob))};recorder.start(1000);const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(SR){const rec=new SR();rec.lang="ja-JP";rec.continuous=true;rec.interimResults=true;rec.onresult=(e:any)=>{let final="";for(let i=e.resultIndex;i<e.results.length;i++)if(e.results[i].isFinal)final+=e.results[i][0].transcript+"。";if(final)setTranscript(t=>{const n=(t+(t?"\n":"")+final).trim();transcriptRef.current=n;return n})};rec.onend=()=>{if(mediaRef.current?.state==="recording")try{rec.start()}catch{}};rec.start();recognitionRef.current=rec}setSeconds(0);setDraft(null);setRecording(true);setStatus("録音・文字起こし中（開始音は鳴りません）");timerRef.current=window.setInterval(()=>setSeconds(s=>s+1),1000)}catch{setStatus("マイクを開始できません。許可を確認するか会話文を貼り付けてください")}};
 const stop=()=>{if(mediaRef.current?.state!=="inactive")mediaRef.current?.stop();recognitionRef.current?.stop?.();streamRef.current?.getTracks().forEach(t=>t.stop());if(timerRef.current)clearInterval(timerRef.current);setRecording(false);setStatus("録音停止。最後の文字を取り込んでいます…");window.setTimeout(()=>analyze(transcriptRef.current),700)};
 const save=async()=>{if(!draft)return;setSaving(true);try{const form=new FormData();form.set("data",JSON.stringify({title,date,participants,transcript,duration:seconds,consentConfirmed,...draft}));if(audioBlobRef.current)form.set("audio",audioBlobRef.current,`meeting-${date}.webm`);const r=await fetch("/api/meeting-minutes",{method:"POST",body:form});const j=await r.json();if(!r.ok)throw new Error(j.error);setStatus("議事録と録音データを保存しました");await load()}catch(e){setStatus(e instanceof Error?e.message:"保存できませんでした")}finally{setSaving(false)}};
 const copy=async()=>{if(!draft)return;await navigator.clipboard.writeText(toText({title,date,participants,duration:seconds,transcript,...draft}));setCopied(true);setTimeout(()=>setCopied(false),1200)};
 const shown=history.filter(x=>!query||[x.title,x.participants,x.summary,...x.decisions,...x.actions.map(a=>a.task),...x.pending].join(" ").toLowerCase().includes(query.toLowerCase()));
 return <div className="page minutesPage productionMinutes"><div className="pageTitle"><div><span className="eyebrow">AI MEETING MINUTES</span><h2>AI議事録</h2><p>録音停止だけで、要約・決定事項・担当者・期限まで整理</p></div><b className={recording?"recordingBadge active":"recordingBadge"}>{recording?"録音中":"本番版"}</b></div>
  <section className="meetingRecorder"><label className="recordConsent"><input type="checkbox" checked={consentConfirmed} onChange={e=>setConsentConfirmed(e.target.checked)}/><span><b>参加者へ録音を説明し、同意を確認しました</b><small>目的・保存期間・共有範囲も伝えてください</small></span></label><div className="recordTop"><div className={recording?"micPulse active":"micPulse"}>●</div><div><b>{formatTime(seconds)}</b><span>{status}</span></div></div><button className={recording?"stopRecord":"startRecord"} onClick={recording?stop:start} disabled={analyzing||(!recording&&!consentConfirmed)}>{recording?"■ 録音を終了して自動整理":"● 録音を開始"}</button><p>開始音は鳴りません。停止すると自動で議事録案を作成し、録音を再生できます。</p></section>
  <section className="minutesMeta"><label>会議名<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>開催日<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>参加者<input value={participants} onChange={e=>setParticipants(e.target.value)} placeholder="例：建築 田中、電気 鈴木、設備 中村"/></label></section>
  {audioUrl&&<section className="audioReview"><div><b>録音データ</b><span>{formatTime(seconds)}</span></div><audio src={audioUrl} controls/></section>}
  <section className="transcriptBox"><div><b>文字起こし（編集できます）</b><span>話者名は「田中：」のように入力</span></div><textarea value={transcript} onChange={e=>{setTranscript(e.target.value);transcriptRef.current=e.target.value}} placeholder="対応端末では録音中に自動文字起こしします。うまく取得できない場合は会話内容を貼り付けてください。"/><button onClick={()=>analyze(transcript)} disabled={analyzing}>{analyzing?"AIが整理中…":"編集した内容でもう一度整理"}</button></section>
  {draft&&<section className="minutesDraft productionDraft"><header><span>{draft.source==="ai"?"AI解析済み":"自動整理"}</span><h3>{title}</h3><p>{date}　録音 {formatTime(seconds)}　{participants}</p></header><label className="editableSummary">要約<textarea value={draft.summary} onChange={e=>setDraft({...draft,summary:e.target.value})}/></label><EditableList title="決定事項" items={draft.decisions} onChange={decisions=>setDraft({...draft,decisions})}/><ActionEditor items={draft.actions} onChange={actions=>setDraft({...draft,actions})}/><EditableList title="未決事項・次回確認" items={draft.pending} onChange={pending=>setDraft({...draft,pending})}/>{draft.speakers.length>0&&<div className="speakerTags"><b>検出した話者</b>{draft.speakers.map(x=><span key={x}>{x}</span>)}</div>}<div className="minutesActions"><button onClick={copy}>{copied?"コピー済み":"議事録をコピー"}</button><button onClick={()=>window.print()}>PDF保存・印刷</button><button className="saveMinutes" onClick={save} disabled={saving}>{saving?"保存中…":"議事録と録音を保存"}</button></div><p className="minutesWarning">共有前に、担当者・期限・金額・寸法・固有名詞を原文と照合してください。</p></section>}
  <section className="minutesHistory"><div className="historyHead"><div><h3>保存した議事録</h3><span>{history.length}件・サイトに保存</span></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="会議名・決定事項・担当者を検索"/></div>{shown.map(x=><details key={x.id}><summary><span><b>{x.title}</b><small>{x.date}　{formatTime(x.duration)}　{x.participants}</small></span><em>開く</em></summary><div><MinuteView minute={x}/>{x.audioUrl&&<audio src={x.audioUrl} controls/>}<div className="savedActions"><button onClick={()=>navigator.clipboard.writeText(toText(x))}>コピー</button><button onClick={()=>window.print()}>PDF保存・印刷</button></div></div></details>)}{!shown.length&&<p className="empty">保存した議事録はありません</p>}</section>
  <p className="caution">音声認識・AI整理は誤認識する場合があります。会議参加者へ録音することを伝え、社内ルールに従って使用してください。</p>
 </div>}
function EditableList({title,items,onChange}:{title:string;items:string[];onChange:(x:string[])=>void}){return <section className="editableList"><div><h4>{title}</h4><button onClick={()=>onChange([...items,""])}>＋追加</button></div>{items.length?items.map((x,i)=><label key={i}><span>{i+1}</span><input value={x} onChange={e=>onChange(items.map((v,n)=>n===i?e.target.value:v))}/><button onClick={()=>onChange(items.filter((_,n)=>n!==i))}>×</button></label>):<p>該当なし</p>}</section>}
function ActionEditor({items,onChange}:{items:ActionItem[];onChange:(x:ActionItem[])=>void}){const update=(i:number,k:keyof ActionItem,v:string)=>onChange(items.map((x,n)=>n===i?{...x,[k]:v}:x));return <section className="actionEditor"><div><h4>担当・期限</h4><button onClick={()=>onChange([...items,{task:"",assignee:"未設定",due:"未設定"}])}>＋追加</button></div>{items.length?items.map((x,i)=><article key={i}><input value={x.task} onChange={e=>update(i,"task",e.target.value)} placeholder="対応内容"/><label>担当<input value={x.assignee} onChange={e=>update(i,"assignee",e.target.value)}/></label><label>期限<input value={x.due} onChange={e=>update(i,"due",e.target.value)}/></label><button onClick={()=>onChange(items.filter((_,n)=>n!==i))}>×</button></article>):<p>担当・期限付きの項目はありません</p>}</section>}
function MinuteView({minute:x}:{minute:Minute}){return <div className="minuteView"><h4>要約</h4><p>{x.summary||"該当なし"}</p><h4>決定事項</h4><ul>{x.decisions.map(v=><li key={v}>{v}</li>)}</ul><h4>担当・期限</h4><ul>{x.actions.map((v,i)=><li key={i}><b>{v.assignee}</b>｜{v.task}｜期限 {v.due}</li>)}</ul><h4>未決事項・次回確認</h4><ul>{x.pending.map(v=><li key={v}>{v}</li>)}</ul><h4>文字起こし原文</h4><p className="originalText">{x.transcript}</p></div>}
function toText(x:{title:string;date:string;participants:string;duration:number;summary:string;decisions:string[];actions:ActionItem[];pending:string[];transcript:string}){return `${x.title}\n${x.date}　録音 ${formatTime(x.duration)}\n参加者：${x.participants||"未入力"}\n\n【要約】\n${x.summary}\n\n【決定事項】\n${x.decisions.map(v=>`・${v}`).join("\n")||"・なし"}\n\n【担当・期限】\n${x.actions.map(v=>`・${v.assignee}｜${v.task}｜期限 ${v.due}`).join("\n")||"・なし"}\n\n【未決事項・次回確認】\n${x.pending.map(v=>`・${v}`).join("\n")||"・なし"}\n\n【文字起こし原文】\n${x.transcript}`}
