"use client";
import {useEffect,useState} from "react";
type Context={user:{email:string;role:string;acceptedTermsVersion:string};project:{id:string;name:string;company:string;siteCode:string};projects:{id:string;name:string;company:string;role:string}[];members:{email:string;role:string}[];settings:{adoptedSystems:Record<string,string>;favoriteMaterials:Record<string,string[]>;manufacturers:Record<string,string>;onboardingCompleted:boolean;meetingAudioRetentionDays:number;recordingConsentRequired:boolean};audit:{id:number;summary:string;actorEmail:string;createdAt:string}[];billing?:{plan:"free"|"pro";isPro:boolean;status:string}};
const quality=[["用途別配管材","用途に合わない管材を除外し、現場採用品をお気に入りで限定","継続確認"],["異種管変換・パッキン","両側の継手、接続方式、流体・温度・圧力を一組で確認","継続確認"],["吊りピッチ・支持","管種・径・保温・満水重量・地震条件で最終確認","継続確認"],["勾配・器具・機器高さ","法令、標準仕様、自治体、承認図の優先順位を表示","継続確認"],["区画貫通","壁床・管材・保温・開口を認定範囲と照合","継続確認"],["歩掛・工程範囲","計画目安として表示し、搬入・墨出し・支持等の範囲を明示","暫定値"]];
export default function ReleaseCenter(){
 const [ctx,setCtx]=useState<Context|null>(null),[loading,setLoading]=useState(true),[upgrading,setUpgrading]=useState(false),[message,setMessage]=useState(""),[form,setForm]=useState({name:"",company:"",siteCode:"",water:"ZlokⅡ",drain:"セキスイ VP・VU",steam:"JFE SGP黒",fire:"SGP白",retention:"90",terms:false}),[feedback,setFeedback]=useState({category:"改善提案",screen:"",detail:"",rating:"0"});
 const load=async()=>{setLoading(true);const r=await fetch("/api/account/context");const j=await r.json();if(r.ok){setCtx(j);setForm(f=>({...f,name:j.project?.name||"",company:j.project?.company||"",siteCode:j.project?.siteCode||"",water:j.settings?.adoptedSystems?.water||"ZlokⅡ",drain:j.settings?.adoptedSystems?.drain||"セキスイ VP・VU",steam:j.settings?.adoptedSystems?.steam||"JFE SGP黒",fire:j.settings?.adoptedSystems?.fire||"SGP白",retention:String(j.settings?.meetingAudioRetentionDays||90),terms:Boolean(j.user?.acceptedTermsVersion)}))}else setMessage(j.error||"ログイン情報を確認できません");setLoading(false)};
 useEffect(()=>{load()},[]);
 const save=async()=>{if(!form.terms){setMessage("利用条件とプライバシー方針への同意が必要です");return}const r=await fetch("/api/account/context",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:form.name,company:form.company,siteCode:form.siteCode,adoptedSystems:{water:form.water,drain:form.drain,steam:form.steam,fire:form.fire},favoriteMaterials:{給水:[form.water],排水:[form.drain],蒸気:[form.steam],消火:[form.fire]},manufacturers:{steel:"JFE",resin:"セキスイ",support:"アカギ"},meetingAudioRetentionDays:Number(form.retention),recordingConsentRequired:true,onboardingCompleted:true,acceptTerms:true})});setMessage(r.ok?"現場設定を保存しました":"保存できませんでした");if(r.ok)load()};
 const backup=async()=>{const r=await fetch("/api/backup");if(!r.ok){setMessage("バックアップを作成できませんでした");return}const blob=await r.blob(),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`設備現場バックアップ-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};
 const restore=async(file:File)=>{const data=JSON.parse(await file.text());const r=await fetch("/api/backup",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)});const j=await r.json();setMessage(r.ok?`${j.count}件を追加復元しました`:j.error)};
 const sendFeedback=async()=>{const r=await fetch("/api/feedback",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(feedback)});setMessage(r.ok?"フィードバックを登録しました":"内容を入力してください");if(r.ok)setFeedback({...feedback,detail:""})};
 const upgrade=async()=>{setUpgrading(true);setMessage("");try{const r=await fetch("/api/billing/checkout",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({interval:"month"})});const j=await r.json();if(!r.ok||!j.url)throw new Error(j.error||"決済画面を開けませんでした");window.location.assign(j.url)}catch(e){setMessage(e instanceof Error?e.message:"決済画面を開けませんでした");setUpgrading(false)}};
 if(loading)return <div className="page releaseCenter"><p>現場設定を読み込んでいます…</p></div>;
 return <div className="page releaseCenter"><div className="pageTitle"><div><span className="eyebrow">RELEASE & TRUST</span><h2>現場設定・品質管理</h2><p>現場データ、採用品、根拠、バックアップ、利用ルールを一か所で管理</p></div><b>{ctx?.user.role||"閲覧"}</b></div>
  {ctx&&ctx.billing?.isPro!==true&&<section className="releaseCard upgradeCard" aria-label="PROプランへのアップグレード"><div><span className="upgradeBadge">現在 FREEプラン</span><h3>設備現場マネージャー PRO</h3><p>全配管材・計算・施工要領・AI機能など、現場向けの全機能を月額980円で利用できます。</p></div><button type="button" onClick={upgrade} disabled={upgrading}>{upgrading?"決済画面を準備中…":"PROにアップグレード 月980円"}</button></section>}
  {message&&<p className="releaseMessage">{message}</p>}
  <section className="releaseCard"><h3>現場の初期設定</h3><div className="releaseGrid"><label>現場名<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>会社名<input value={form.company} onChange={e=>setForm({...form,company:e.target.value})}/></label><label>現場コード<input value={form.siteCode} onChange={e=>setForm({...form,siteCode:e.target.value})}/></label><label>給水の採用品<input value={form.water} onChange={e=>setForm({...form,water:e.target.value})}/></label><label>排水の採用品<input value={form.drain} onChange={e=>setForm({...form,drain:e.target.value})}/></label><label>蒸気の採用品<input value={form.steam} onChange={e=>setForm({...form,steam:e.target.value})}/></label><label>消火の採用品<input value={form.fire} onChange={e=>setForm({...form,fire:e.target.value})}/></label><label>録音保存期間<select value={form.retention} onChange={e=>setForm({...form,retention:e.target.value})}><option value="30">30日</option><option value="90">90日</option><option value="365">1年</option></select></label></div><label className="termsCheck"><input type="checkbox" checked={form.terms} onChange={e=>setForm({...form,terms:e.target.checked})}/>利用条件・プライバシー方針・録音ルールを確認し同意する</label><button onClick={save}>設定を保存</button></section>
  <section className="releaseCard"><h3>データ保護・復元</h3><p>ToDo、工程、材料、区画貫通、設定、議事録メタデータを現場単位で保存します。PDF・録音本体はアクセス制限された別領域に保存されます。</p><div className="releaseActions"><button onClick={backup}>バックアップをダウンロード</button><label className="fileButton">バックアップを追加復元<input type="file" accept="application/json" onChange={e=>e.target.files?.[0]&&restore(e.target.files[0])}/></label></div></section>
  <section className="releaseCard"><h3>情報の信頼性</h3><div className="qualityTable">{quality.map(x=><article key={x[0]}><div><b>{x[0]}</b><p>{x[1]}</p></div><span>{x[2]}</span></article>)}</div><p className="releaseNote">表示区分：法令・公的基準／標準仕様／メーカー公式／一般的な目安／設計・承認図優先。歩掛は工程計画用の暫定値であり、実績で補正してください。</p></section>
  <section className="releaseCard legal"><h3>利用条件・プライバシー・免責</h3><details><summary>利用条件</summary><p>本サービスは設備工事の検討・記録を補助します。施工確定、法令適合、製品選定、数量・工程の最終判断は、設計図書、特記仕様、承認図、所轄官庁、資格者および採用メーカーの最新版で確認してください。</p></details><details><summary>個人情報・現場情報</summary><p>現場名、担当者、資料、文字起こし、録音を保存します。必要最小限を入力し、権限のない第三者の情報や機密を登録しないでください。現場単位で分離し、操作履歴を記録します。</p></details><details><summary>AIと録音</summary><p>AI出力には誤りがあり得ます。共有前に原文・数値・固有名詞を照合してください。録音前に参加者へ目的・保存期間・共有範囲を伝え、同意を確認してください。停止時は自動整理されますが、保存は確認後に行います。</p></details></section>
  <section className="releaseCard"><h3>現場テスト・改善報告</h3><p>実際の監督・職長に使ってもらい、画面名と状況を具体的に記録してください。</p><div className="releaseGrid"><label>種類<select value={feedback.category} onChange={e=>setFeedback({...feedback,category:e.target.value})}><option>不具合</option><option>誤情報</option><option>使いにくい</option><option>改善提案</option></select></label><label>画面<input value={feedback.screen} onChange={e=>setFeedback({...feedback,screen:e.target.value})} placeholder="例：配管材"/></label></div><textarea value={feedback.detail} onChange={e=>setFeedback({...feedback,detail:e.target.value})} placeholder="操作、期待した結果、実際の結果"/><button onClick={sendFeedback}>改善報告を登録</button></section>
  <section className="releaseCard"><h3>操作・修正履歴</h3>{ctx?.audit?.length?ctx.audit.map(x=><p className="auditRow" key={x.id}><b>{x.summary}</b><span>{x.actorEmail}・{new Date(x.createdAt).toLocaleString("ja-JP")}</span></p>):<p>履歴はまだありません。</p>}</section>
 </div>
}
