import {integer,sqliteTable,text,uniqueIndex,index} from "drizzle-orm/sqlite-core";

const scoped={projectId:text("project_id").notNull().default("")};
export const tasks=sqliteTable("tasks",{...scoped,id:integer("id").primaryKey({autoIncrement:true}),title:text("title").notNull(),location:text("location").notNull().default(""),assignee:text("assignee").notNull().default(""),dueDate:text("due_date").notNull().default(""),priority:text("priority").notNull().default("中"),progress:text("progress").notNull().default("前"),status:text("status").notNull().default("未着手"),createdAt:text("created_at").notNull().default("")},t=>[index("tasks_project_idx").on(t.projectId)]);
export const schedules=sqliteTable("schedules",{...scoped,id:integer("id").primaryKey({autoIncrement:true}),name:text("name").notNull(),location:text("location").notNull().default(""),unit:text("unit").notNull().default("m"),quantity:integer("quantity").notNull().default(0),laborRate:integer("labor_rate").notNull().default(0),factor:integer("factor").notNull().default(100),crew:integer("crew").notNull().default(1),utilization:integer("utilization").notNull().default(85),startDate:text("start_date").notNull().default(""),actualQuantity:integer("actual_quantity").notNull().default(0),scope:text("scope").notNull().default(""),scopeDetail:text("scope_detail").notNull().default(""),createdAt:text("created_at").notNull().default("")},t=>[index("schedules_project_idx").on(t.projectId)]);
export const materials=sqliteTable("materials",{...scoped,id:integer("id").primaryKey({autoIncrement:true}),name:text("name").notNull(),pipeType:text("pipe_type").notNull().default(""),size:text("size").notNull().default(""),quantity:integer("quantity").notNull().default(0),unit:text("unit").notNull().default("個"),vendor:text("vendor").notNull().default(""),status:text("status").notNull().default("未発注"),neededDate:text("needed_date").notNull().default(""),note:text("note").notNull().default(""),createdAt:text("created_at").notNull().default("")},t=>[index("materials_project_idx").on(t.projectId)]);
export const penetrations=sqliteTable("penetrations",{...scoped,id:integer("id").primaryKey({autoIncrement:true}),penetrationNo:text("penetration_no").notNull(),floor:text("floor").notNull().default(""),location:text("location").notNull().default(""),compartmentType:text("compartment_type").notNull().default("防火区画"),penetratingItem:text("penetrating_item").notNull().default("配管"),pipeType:text("pipe_type").notNull().default(""),size:text("size").notNull().default(""),openingSize:text("opening_size").notNull().default(""),method:text("method").notNull().default(""),approvalNo:text("approval_no").notNull().default(""),constructionDate:text("construction_date").notNull().default(""),inspectionDate:text("inspection_date").notNull().default(""),photoNo:text("photo_no").notNull().default(""),status:text("status").notNull().default("未施工"),note:text("note").notNull().default(""),createdAt:text("created_at").notNull().default("")},t=>[index("penetrations_project_idx").on(t.projectId)]);
export const documents=sqliteTable("documents",{...scoped,id:integer("id").primaryKey({autoIncrement:true}),name:text("name").notNull(),category:text("category").notNull().default("施工計画書"),fileName:text("file_name").notNull(),objectKey:text("object_key").notNull(),contentType:text("content_type").notNull().default("application/pdf"),fileSize:integer("file_size").notNull().default(0),pageCount:integer("page_count").notNull().default(0),extractedText:text("extracted_text").notNull().default(""),status:text("status").notNull().default("読取済み"),sharing:text("sharing").notNull().default("自社のみ"),createdAt:text("created_at").notNull().default("")},t=>[index("documents_project_idx").on(t.projectId)]);
export const knowledgeReports=sqliteTable("knowledge_reports",{...scoped,id:integer("id").primaryKey({autoIncrement:true}),subject:text("subject").notNull(),category:text("category").notNull().default("施工ルール"),reportType:text("report_type").notNull().default("誤りの可能性"),detail:text("detail").notNull(),sourceUrl:text("source_url").notNull().default(""),status:text("status").notNull().default("未確認"),resolution:text("resolution").notNull().default(""),createdAt:text("created_at").notNull().default(""),updatedAt:text("updated_at").notNull().default("")},t=>[index("knowledge_project_idx").on(t.projectId)]);
export const meetingMinutes=sqliteTable("meeting_minutes",{...scoped,id:integer("id").primaryKey({autoIncrement:true}),title:text("title").notNull(),meetingDate:text("meeting_date").notNull().default(""),participants:text("participants").notNull().default(""),duration:integer("duration").notNull().default(0),transcript:text("transcript").notNull(),summary:text("summary").notNull().default(""),decisions:text("decisions").notNull().default("[]"),actions:text("actions").notNull().default("[]"),pending:text("pending").notNull().default("[]"),speakers:text("speakers").notNull().default("[]"),analysisSource:text("analysis_source").notNull().default("local"),audioObjectKey:text("audio_object_key").notNull().default(""),audioContentType:text("audio_content_type").notNull().default(""),consentConfirmed:integer("consent_confirmed",{mode:"boolean"}).notNull().default(false),retentionUntil:text("retention_until").notNull().default(""),createdAt:text("created_at").notNull().default("")},t=>[index("minutes_project_idx").on(t.projectId)]);

export const projects=sqliteTable("projects",{id:text("id").primaryKey(),ownerEmail:text("owner_email").notNull(),name:text("name").notNull(),company:text("company").notNull().default(""),siteCode:text("site_code").notNull().default(""),createdAt:text("created_at").notNull(),updatedAt:text("updated_at").notNull()});
export const projectMembers=sqliteTable("project_members",{id:integer("id").primaryKey({autoIncrement:true}),projectId:text("project_id").notNull(),email:text("email").notNull(),role:text("role").notNull().default("viewer"),createdAt:text("created_at").notNull()},t=>[uniqueIndex("project_member_unique").on(t.projectId,t.email),index("member_email_idx").on(t.email)]);
export const userSettings=sqliteTable("user_settings",{email:text("email").primaryKey(),activeProjectId:text("active_project_id").notNull().default(""),acceptedTermsVersion:text("accepted_terms_version").notNull().default(""),acceptedAt:text("accepted_at").notNull().default(""),createdAt:text("created_at").notNull(),updatedAt:text("updated_at").notNull()});
export const projectSettings=sqliteTable("project_settings",{projectId:text("project_id").primaryKey(),adoptedSystems:text("adopted_systems").notNull().default("{}"),favoriteMaterials:text("favorite_materials").notNull().default("{}"),manufacturers:text("manufacturers").notNull().default("{}"),onboardingCompleted:integer("onboarding_completed",{mode:"boolean"}).notNull().default(false),meetingAudioRetentionDays:integer("meeting_audio_retention_days").notNull().default(90),recordingConsentRequired:integer("recording_consent_required",{mode:"boolean"}).notNull().default(true),updatedAt:text("updated_at").notNull()});
export const auditLogs=sqliteTable("audit_logs",{id:integer("id").primaryKey({autoIncrement:true}),projectId:text("project_id").notNull(),actorEmail:text("actor_email").notNull(),action:text("action").notNull(),entityType:text("entity_type").notNull(),entityId:text("entity_id").notNull().default(""),summary:text("summary").notNull().default(""),beforeJson:text("before_json").notNull().default(""),afterJson:text("after_json").notNull().default(""),createdAt:text("created_at").notNull()},t=>[index("audit_project_idx").on(t.projectId)]);
export const feedback=sqliteTable("feedback",{id:integer("id").primaryKey({autoIncrement:true}),projectId:text("project_id").notNull(),userEmail:text("user_email").notNull(),category:text("category").notNull().default("改善提案"),screen:text("screen").notNull().default(""),detail:text("detail").notNull(),rating:integer("rating").notNull().default(0),status:text("status").notNull().default("未対応"),createdAt:text("created_at").notNull(),updatedAt:text("updated_at").notNull()},t=>[index("feedback_project_idx").on(t.projectId)]);
export const knowledgeRevisions=sqliteTable("knowledge_revisions",{id:integer("id").primaryKey({autoIncrement:true}),projectId:text("project_id").notNull(),subject:text("subject").notNull(),category:text("category").notNull(),changeSummary:text("change_summary").notNull(),basisType:text("basis_type").notNull().default("一般的な目安"),sourceUrl:text("source_url").notNull().default(""),checkedAt:text("checked_at").notNull().default(""),actorEmail:text("actor_email").notNull(),createdAt:text("created_at").notNull()},t=>[index("revision_project_idx").on(t.projectId)]);


export const subscriptions=sqliteTable("subscriptions",{
 email:text("email").primaryKey(),
 plan:text("plan").notNull().default("free"),
 status:text("status").notNull().default("inactive"),
 billingInterval:text("billing_interval").notNull().default("month"),
 stripeCustomerId:text("stripe_customer_id").notNull().default(""),
 stripeSubscriptionId:text("stripe_subscription_id").notNull().default(""),
 currentPeriodEnd:text("current_period_end").notNull().default(""),
 cancelAtPeriodEnd:integer("cancel_at_period_end",{mode:"boolean"}).notNull().default(false),
 createdAt:text("created_at").notNull(),
 updatedAt:text("updated_at").notNull()
},t=>[
 uniqueIndex("subscription_customer_unique").on(t.stripeCustomerId),
 uniqueIndex("subscription_stripe_unique").on(t.stripeSubscriptionId)
]);
