import {and,desc,eq} from "drizzle-orm";
import {apiError,audit,requireContext,requireEditor} from "@/lib/request-context";
import {auditLogs,projectMembers,projects,projectSettings,userSettings} from "@/db/schema";
import {getBillingSummary} from "@/lib/billing";
const parse=(x:string)=>{try{return JSON.parse(x||"{}")}catch{return{}}};
export async function GET(req:Request){try{const ctx=await requireContext(req);const project=await ctx.db.query.projects.findFirst({where:eq(projects.id,ctx.projectId)});const settings=await ctx.db.query.projectSettings.findFirst({where:eq(projectSettings.projectId,ctx.projectId)});const user=await ctx.db.query.userSettings.findFirst({where:eq(userSettings.email,ctx.email)});const memberships=await ctx.db.select({id:projects.id,name:projects.name,company:projects.company,role:projectMembers.role}).from(projectMembers).innerJoin(projects,eq(projectMembers.projectId,projects.id)).where(eq(projectMembers.email,ctx.email));const members=await ctx.db.select().from(projectMembers).where(eq(projectMembers.projectId,ctx.projectId));const recent=await ctx.db.select().from(auditLogs).where(eq(auditLogs.projectId,ctx.projectId)).orderBy(desc(auditLogs.id)).limit(30);const billing=await getBillingSummary(ctx);return Response.json({user:{email:ctx.email,role:ctx.role,acceptedTermsVersion:user?.acceptedTermsVersion||""},billing,project,projects:memberships,members,settings:settings?{...settings,adoptedSystems:parse(settings.adoptedSystems),favoriteMaterials:parse(settings.favoriteMaterials),manufacturers:parse(settings.manufacturers)}:null,audit:recent})}catch(e){return apiError(e)}}
export async function POST(req:Request){try{const ctx=await requireContext(req);requireEditor(ctx);const p=await req.json() as any;const t=new Date().toISOString();
 if(p.action==="switch"){const member=await ctx.db.query.projectMembers.findFirst({where:and(eq(projectMembers.projectId,String(p.projectId)),eq(projectMembers.email,ctx.email))});if(!member)return Response.json({error:"この現場へアクセスできません"},{status:403});await ctx.db.update(userSettings).set({activeProjectId:String(p.projectId),updatedAt:t}).where(eq(userSettings.email,ctx.email));return Response.json({ok:true})}
 if(p.action==="create"){const id=crypto.randomUUID();await ctx.db.insert(projects).values({id,ownerEmail:ctx.email,name:String(p.name||"新しい現場"),company:String(p.company||""),siteCode:String(p.siteCode||""),createdAt:t,updatedAt:t});await ctx.db.insert(projectMembers).values({projectId:id,email:ctx.email,role:"owner",createdAt:t});await ctx.db.insert(projectSettings).values({projectId:id,updatedAt:t});await ctx.db.update(userSettings).set({activeProjectId:id,updatedAt:t}).where(eq(userSettings.email,ctx.email));return Response.json({ok:true,projectId:id},{status:201})}
 await ctx.db.update(projects).set({name:String(p.name||"設備工事現場"),company:String(p.company||""),siteCode:String(p.siteCode||""),updatedAt:t}).where(eq(projects.id,ctx.projectId));
 await ctx.db.update(projectSettings).set({adoptedSystems:JSON.stringify(p.adoptedSystems||{}),favoriteMaterials:JSON.stringify(p.favoriteMaterials||{}),manufacturers:JSON.stringify(p.manufacturers||{}),onboardingCompleted:Boolean(p.onboardingCompleted),meetingAudioRetentionDays:Number(p.meetingAudioRetentionDays)||90,recordingConsentRequired:p.recordingConsentRequired!==false,updatedAt:t}).where(eq(projectSettings.projectId,ctx.projectId));
 if(p.acceptTerms){await ctx.db.update(userSettings).set({acceptedTermsVersion:"2026-08-23",acceptedAt:t,updatedAt:t}).where(eq(userSettings.email,ctx.email))}
 await audit(ctx,"update","project",ctx.projectId,"現場設定を更新");return Response.json({ok:true});
 }catch(e){return apiError(e)}}
